TASK.8

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.metrics import accuracy_score


In [14]:
iris = load_iris()

X = iris.data        # Independent variables
y = iris.target     # Dependent variable


In [4]:
from sklearn.datasets import load_iris


In [5]:
iris = load_iris()


In [6]:
X = iris.data      # Features
y = iris.target   # Labels


In [7]:
print(X[:5])
print(y[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [9]:
# Train-test split (80:20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [10]:
#Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)
print("GaussianNB Accuracy:", accuracy_score(y_test, y_pred_gnb))


GaussianNB Accuracy: 1.0


In [11]:
#Bernoulli Naive Bayes

# Convert to binary
X_train_bin = np.where(X_train > X_train.mean(), 1, 0)
X_test_bin = np.where(X_test > X_train.mean(), 1, 0)

bnb = BernoulliNB()
bnb.fit(X_train_bin, y_train)
y_pred_bnb = bnb.predict(X_test_bin)
print("BernoulliNB Accuracy:", accuracy_score(y_test, y_pred_bnb))


BernoulliNB Accuracy: 0.6666666666666666


In [12]:
#Multinominal Navie Bayes

mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred_mnb = mnb.predict(X_test)
print("MultinomialNB Accuracy:", accuracy_score(y_test, y_pred_mnb))


MultinomialNB Accuracy: 0.9


In [17]:
print("MultinomialNB Accuracy:", accuracy_score(y_test, y_pred_mnb))


MultinomialNB Accuracy: 0.9


In [19]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()        # Step 1: define model
model.fit(X_train, y_train)  # Step 2: train




GaussianNB()

In [20]:
model.fit(X_train, y_train)


GaussianNB()

In [21]:
y_pred = model.predict(X_test)


In [22]:
#Check the accuracy
accuracy_score(y_test, y_pred)


1.0