TASK 4

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
#2) arrays in numpy
import numpy as np
#using array 
a = np.array([1, 2, 3, 4])
#Zeros 
b = np.zeros(5)
# ones
c = np.ones(3)
#arange
d = np.arange(1, 10, 2)
#Linspace
e = np.linspace(0, 1, 5)
print(a, b, c, d, e)

[1 2 3 4] [0. 0. 0. 0. 0.] [1. 1. 1.] [1 3 5 7 9] [0.   0.25 0.5  0.75 1.  ]


In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    
print(arr[1:4])   # Slicing


10
[20 30 40]


In [5]:
#3 Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


In [7]:
print(np.sqrt(arr))
print(np.sin(arr))
print(np.exp(arr))


[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]


In [17]:
#4 Array shapes and 

# shape and dimensions
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.ndim)


(2, 3)
2


In [9]:
#Reshape,Flatten, Transpose
print(arr.reshape(3, 2))
print(arr.flatten())
print(arr.transpose())


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [10]:
#Concatenation and splitting
a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))
print(np.vstack((a, b)))
print(np.hstack((a, b)))

arr = np.array([1, 2, 3, 4])
print(np.split(arr, 2))


[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4])]


In [11]:
# Array Manipulation
#multi-dimensional indexing
arr = np.array([[1, 2], [3, 4]])
print(arr[0, 1])


2


In [12]:
# Masking (Boolean Indexing)
arr = np.array([10, 20, 30, 40])
print(arr[arr > 20])


[30 40]


In [13]:
#Fancy Indexing
arr = np.array([10, 20, 30, 40])
print(arr[[0, 2]])


[10 30]


In [15]:
# Mathematical Functions 
#universal functions (ufuncs)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [16]:
#statistical function
data = np.array([10, 20, 30, 40, 50])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))
print(np.min(data))
print(np.max(data))


30.0
30.0
14.142135623730951
200.0
10
50


In [18]:
#Linear algebra
mat = np.array([[1, 2], [3, 4]])

print(np.dot(mat, mat))
print(np.linalg.inv(mat))
print(np.linalg.eig(mat))


[[ 7 10]
 [15 22]]
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [19]:
#Random Number Generation
np.random.seed(10)

print(np.random.rand(3))
print(np.random.randint(1, 10, 5))

arr = np.array([1, 2, 3, 4])
np.random.shuffle(arr)
print(arr)

print(np.random.permutation(arr))


[0.77132064 0.02075195 0.63364823]
[1 2 9 1 9]
[4 2 1 3]
[1 2 3 4]


In [25]:
#Broadcasting
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]
